version: '3.9'

services:
  dynamodb-local:
    container_name: dynamodb_local
    image: amazon/dynamodb-local
    ports:
      - '8085:8000'
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./dynamodb_data:/data # 修正
    networks:
      - local-dev-net
    restart: unless-stopped
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000 # 修正
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - local-dev-net # 修正

networks:
  local-dev-net:
    driver: bridge

volumes:
  dynamodb_data: